<?php

class IconsFilter extends WireData implements Module {

    /**
     * Module information
     */
    public static function getModuleInfo() {
        return array(
            'title' => 'Icons Filter',
            'version' => 1,
            'summary' => 'Allows the "all icons" view in InputfieldIcon to be filtered by name.',
            'author' => 'Robin Sallis',
            'autoload' => "template=admin",
        );
    }

    /**
     * Ready
     */
    public function ready() {
        $this->addHookAfter('InputfieldIcon::render', $this, 'addExtras');
    }

    /**
     * Add script and stylesheet
     */
    public function addExtras($event) {
        $info = $this->getModuleInfo();
        $version = $info['version'];
        $out = $event->return;
        $modulePath = $this->config->urls->siteModules . "IconsFilter/";
        $out .= "<script src='{$modulePath}IconsFilter.js?v=$version'></script>";
        $out .= "<link rel='stylesheet' href='{$modulePath}IconsFilter.css?v=$version'>";
        $event->return = $out;
    }

}
